apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gke-test-hpa
  namespace: default
  labels:
    app: gke-test-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: gke-test-deployment
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80