apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-test-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi